name: Deploy Flask App and Auto Merge PR

on:
  pull_request_target:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - edited
      - ready_for_review
      - unlabeled
      - labeled
      - unlocked

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout repository code
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: refs/pull/${{ github.event.pull_request.number }}/merge

      # Step 2: Setup Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run tests
      - name: Run tests
        run: make test
        env:
          THIS_SECRET: ${{ secrets.THIS_SECRET }}

  automerge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      # Step 1: Checkout repository code
      - name: Checkout Code
        uses: actions/checkout@v2

      # Step 2: Automerge PR if conditions are met
      - id: automerge
        name: Automerge PR
        uses: pascalgn/automerge-action@v0.16.4
        env:
          GITHUB_TOKEN: "${{ secrets.THIS_SECRET }}"  # Use your custom secret here
