name: Deploy Flask App Workflow

on:
  pull_request_target:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Step 1 Checkout reppo codne
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: refs/pull/${{ github.event.pull_request.number }}/merge
      
    
    # Step 2 Setup Python Environmentt
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
    
    # Step 3 Install dependencess
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: run tests
        run: make test
        env:
          THIS_SECRET: ${{ secrets.THIS_SECRET }}

  